name: release

on:
  push:
    branches:
      - uswc

permissions:
  contents: write
  pull-requests: write
  packages: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies with Bun
        run: bun install

      - name: Build openauth package
        run: bun run --filter="@openauthjs/openauth" build

      # Setup Node so that npm publish works properly.
      - name: Setup Node for publishing
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'

      # Create an .npmrc file inside the package directory for GitHub Packages authentication
      - name: Configure npm for GitHub Packages
        run: |
          echo "@openauthjs:registry=https://npm.pkg.github.com" > packages/openauth/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> packages/openauth/.npmrc

      - name: Publish openauth package
        working-directory: packages/openauth
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
